### ISSUE TITLE
Cuda error: cudaMalloc octor failed: out of memory.

### ISSUE THREAD

**Issue by antithing** [botforge/CUDA-ScanMatcher-ICP#1]
Hi, and thank you for making this code available.

I am running it on a laptop, with a GTX 1070 with :

```
#define VISUALIZE 1
#define STEP true
#define CPU false
#define GPU_NAIVE false
#define GPU_OCTREE true
#define MODEL true;
#define UNIFORM_GRID 0
#define COHERENT_GRID 0
```

and I get the error:

```
OPENING MODEL
Line 98: Cuda error: cudaMalloc octor failed: out of memory.
```

I have set the blocksize lower:

`#define blockSize 16`

but it does not help.

What can I look at to get this code running?

Thank you!

**Comment by botforge** [comment]
Hi! How much VRAM do you have?

**Comment by antithing** [comment]
Hi! Thanks for getting back to me.
Spec below:

![image](https://user-images.githubusercontent.com/11506730/67623952-41068180-f823-11e9-9273-3781b8fb86bb.png)


![image](https://user-images.githubusercontent.com/11506730/67623975-71e6b680-f823-11e9-8950-d6c250b77c40.png)

**Comment by botforge** [comment]
Hey @antithing, VRAM refers to GPU memory. I'm not entirely sure that image tells you how much VRAM you have.
This [tutorial ](https://www.laptopmag.com/articles/check-vram-windows-10) should help you see how much VRAM you have.
Also, could you try it with ``GPU_NAIVE true`` and ``GPU_OCTREE false``? I want to see where the issue stems from, as it appears to be from mallocing the octree on the GPU.

**Comment by antithing** [comment]
Thanks!

![image](https://user-images.githubusercontent.com/11506730/67624076-57610d00-f824-11e9-824f-8a5c50da2823.png)


is the gpu spec.


Running with
```

#define GPU_NAIVE true
#define GPU_OCTREE false

```
gives me:

OPENING MODEL
Line 246: Cuda error: cudaMalloc dev_pos failed: out of memory.

**Comment by antithing** [comment]
Weirdly, running with `CPU=true` and `MODEL=true` gives me:

```
OPENING MODEL
file shaders/boid.vert.glsl loaded
file shaders/boid.geom.glsl loaded
file shaders/boid.frag.glsl loaded
0
Line 200: Cuda error: cudaMalloc Pointcloud failed!: invalid argument.
```

**Comment by botforge** [comment]
That is to be expected. The CPU implementation is Naive and I really just used that for basic benchmarking, so I didn't make a loader with it. Let's try something simpler. Set `CPU=false`, `MODEL=false` and `GPU_NAIVE=True` and `GPU_Octree=False`. You should see a Sine wave kind of align.

**Comment by antithing** [comment]
```
#define VISUALIZE 1
#define STEP true
#define CPU false
#define GPU_NAIVE true
#define GPU_OCTREE false
#define MODEL false;
#define UNIFORM_GRID 0
#define COHERENT_GRID 0
```

gives me a window, and a sine wave! It does not align, but I see it.

![image](https://user-images.githubusercontent.com/11506730/67624200-a8bdcc00-f825-11e9-9a2c-d5a8c835e59d.png)

**Comment by botforge** [comment]
Yeah, the iterative closest point algorithm, in general, gets stuck at local minima sometimes, especially with really low-res point clouds. Ok. Let's take it up a notch. Set `CPU=False`, `GPU_Naive=True`, `GPU_Octree=False`, `MODEL=True`. Next, look at 37 of `main.cpp`, and make the function `void parseModel` look like this: 
```C++
void parseModel() {
	int counter = 0;
	//std::ifstream waymoFile("../bigwaymo.txt");
	//std::ifstream waymoFile("../buddha.ply");
	std::ifstream waymoFile("../bunny.ply");
	std::string line;
	printf("OPENING MODEL \n");
	float x, y, z;
	while (std::getline(waymoFile, line)) {
		//std::cout << line << std::endl;
		std::stringstream ss(line);
		ss >> x;
		ss >> y;
		ss >> z;
		glm::vec3 point(x, y, z);
		point *= 20.f;
		coords.push_back(point);
		++counter;
	}
  N_FOR_VIS = counter * 2;
  TRUE_N = N_FOR_VIS / 2;
}
```
The ``bunny.ply`` file contains way fewer points than ``bigwaymo.txt``. Its clear that your issue is that you are running out of GPU memory. For reference, this is what I get:
![image](https://user-images.githubusercontent.com/20353925/67624287-be6acb80-f7fc-11e9-947a-7432e40c2276.png)

**Comment by antithing** [comment]
YES! I see a bunny! 

It is very small in the viewer, but I see it and i think it aligns. Can i zoom in that viewer?

**Comment by botforge** [comment]
YES! Right click and scroll to zoom :) Left click to move the camera around.

**Comment by antithing** [comment]
The counter at the top of the window says 16 fps, however! Is that the actual rate, or the window refresh?

To get timings, i should time the `  runCUDA();` function, correct?

To clarify, I would like print the time it takes for alignment. 

THANK YOU very much for your help and code!

**Comment by botforge** [comment]
Timings vary greatly from device to device. I'll benchmark with Stanford Bunny right now with ``GPU_Naive``. Its also already calculating timings for you. Go to ``scanmatch.cu``, and search for ``duration``. You should see the following set of code repeated in several places:
```C++
	auto start = std::chrono::high_resolution_clock::now();
	ScanMatch::findNNGPU_NAIVE(src_pc, target_pc, dist, indicies, numObjects);
	cudaDeviceSynchronize();
	auto end = std::chrono::high_resolution_clock::now();
	auto duration = std::chrono::duration_cast<std::chrono::microseconds>(end - start); 
	ScanMatch::reshuffleGPU(target_pc, indicies, numObjects);
``` 
Simply print the ``duration`` output for ``void ScanMatch::stepICPGPU_NAIVE()`` and you should be good to go. The octree works really well for planar LiDARs too, but is for some reason sensitive to initialization for the Stanford mesh files. 
UPDATE: I'm hitting close to 60 FPS for the Stanford Bunny on my device after about 1 second of initialization:
![image](https://user-images.githubusercontent.com/20353925/67624428-6e8d0400-f7fe-11e9-8b91-6e8deed0ffe4.png)

UPDATE2: If you want to time alignment, that's going to take some slightly extra work, as the ``runCUDA`` function keeps getting called as long as the two-point clouds are open. I'd recommend looking at the code for ``stepICPUCPU`` and ``findNNCPU``. A good way to measure 'alignment' is to check the mean ``minDist``, and ensure that it is smaller than some ``epsilon``. I'll add that as an option soon. 

I'll test on other devices once my semester ends for sure. This was for a week-long class project so I didn't get the time to do so.

**Comment by antithing** [comment]
Thanks again.  :)
