### ISSUE TITLE
License type?

### ISSUE THREAD

**Issue by sazeci** [botforge/CUDA-ScanMatcher-ICP#4]
Good evening,
what kind of license is applied on this Repo? 
I found on the internet [No License](https://choosealicense.com/no-permission/) is applied on git repos by default, but this licese is quite restricted.
So please provide license of your repo. In my opinion [ICS](https://choosealicense.com/licenses/isc/) or [MIT](https://choosealicense.com/licenses/mit/) would be fine.

Thank you

**Comment by botforge** [comment]
Sure I'll change it to MIT. Use it how you want, and let me know how it helps!
